version: '3'

services: 
    db:
        image: ayushkhajanchi/emor-ecommerce_db:latest
        environment: 
            MYSQL_ROOT_PASSWORD: password
            
        # volumes: 
        #     - ./database:/var/lib/mysql
        ports: 
            - 3306:3306
    backend:
        image: ayushkhajanchi/ecommerce-backend:latest
        # build: "./backend"
        depends_on: 
            - db
        ports: 
            - 8080:8080

    frontend:
        image: ayushkhajanchi/ecommerce:latest
        # build: "./frontend"
        depends_on: 
            - backend
        ports: 
            - 80:80