version: '3'

services: 
    db:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: password
        volumes: 
            - ./database:/var/lib/mysql
    backend:
        image: ecommerce-backend:latest
        build: "./backend"
        depends_on: 
            - db

    frontend:
        image: ecommerce:latest
        build: "./frontend"
        depends_on: 
            - backend
            - db